### ISSUE TITLE
Explicitly named exports should be exported over `export *` exports

### ISSUE THREAD

**Issue by timfish** [DataDog/import-in-the-middle#102]
@mohd-akram and I incorrectly deduced that duplicate named exports resulted in those exports being excluded.

However, this is not always the case!

With the following code:
`a.mjs`
```ts
export function foo() { return 'a' }
```
`b.mjs`
```ts
export function foo() { return 'b' }
```
`dupe.mjs`
```ts
// the order here doesn't matter!
export * from './a.mjs'
export { foo } from './b.mjs'
```
`test.mjs`
```ts
import { foo } from './dupe.mjs'
console.log('out:', foo())
```
```
> node test.mjs
out: b
```

`dupe.mjs` should export `foo` from `b.mjs`. This is because explicitly named exports DO override `export *` exports.

**Comment by jsumners-nr** [comment]
Nice.

<details>
<summary>It continues</summary>

![image](https://github.com/DataDog/import-in-the-middle/assets/150050532/0b101fd6-67b9-461e-b076-5ebe692b10bb)


</details>

**Comment by timfish** [comment]
> It continues

Will it ever end!

**Comment by jsumners-nr** [comment]
> Will it ever end!

No. https://github.com/tc39/proposal-defer-import-eval
