### ISSUE TITLE
Can it be used to hook imports in react app

### ISSUE THREAD

**Issue by re-Tick** [DataDog/import-in-the-middle#15]
## Expected Behavior
Integerate it in a react app to hook axios but the logic is not being executed. Expected "in Hooks" to logged.
```
import Hook from "import-in-the-middle"
Hook(["axios"], (exports, name, baseDir) => {
  console.log("in hook of axios")
})
import axios from 'axios';
```

## Actual Behavior
Nothing is logged.

## Specifications

  - Version: 
  - Platform: React.js
  - Subsystem:

**Comment by bengl** [comment]
@re-Tick Note that the loader hook must be used, i.e. `--loader=import-in-the-middle/hook.mjs`. By putting your example in a file and running it with this command-line parameter, I was able to see the log message.

I'll close this, but please feel free to comment again if you think it's not yet resolved.
