### ISSUE TITLE
Cannot handle node import assertions

### ISSUE THREAD

**Issue by jamesone** [DataDog/import-in-the-middle#24]
## Expected Behavior

Import assertions should be parsed correctly. 

i.e. `import contracts from './package.json' assert { type: 'json' };` 

## Actual Behavior

When using the dd-trace/loader-hook.mjs, the nodejs server is unable to start due to the `import-in-the-middle` package failing to parse import assertions. Here is the related issue https://github.com/DataDog/dd-trace-js/issues/2221#issuecomment-1243122554 

```
TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module "file:///Users/james/dev/myproject/build/package.json" needs an import assertion of type "json"
    at new NodeError (node:internal/errors:372:5)
    at validateAssertions (node:internal/modules/esm/assert:82:15)
    at defaultLoad (node:internal/modules/esm/load:24:3)
    at load (file:///Users/james/dev/myproject/node_modules/import-in-the-middle/hook.mjs:154:10)
    at ESMLoader.load (node:internal/modules/esm/loader:407:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:326:22)
    at new ModuleJob (node:internal/modules/esm/module_job:66:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:345:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:304:34)
    at async Promise.all (index 0) {
  code: 'ERR_IMPORT_ASSERTION_TYPE_MISSING'
}
```

**Note: ** When running node without the dd-trace/loader-hook.mjs, it runs fine (however, [this issue still remains](https://github.com/DataDog/dd-trace-js/issues/2221#issuecomment-1243122554))

## Steps to Reproduce the Problem

  1. `node --experimental-specifier-resolution=node --experimental-loader dd-trace/loader-hook build/src/index.js` - Use the dd-trace/loader-hook in an esm environment. In your build, ensure you have an import assertion, i.e. `import contracts from './package.json' assert { type: 'json' };` 
  2. Run the node command above ^ and 

## Specifications

  - Version: dd-trace -> 3.2.0, node 17.1.0 (also tried on 16.17.0)
  - Platform: MacOS 11.6.4
  - Subsystem:

## Further notes

- I tried using the latest code released today: https://github.com/DataDog/import-in-the-middle/commit/3d77da2612916f493a19fe0c37bd2ab30dec5acb - but this doesn't change anything

**Comment by tlhunter** [comment]
I was able to reproduce this locally. Will be looking into it today.

**Comment by jamesone** [comment]
@tlhunter I can confirm this is working (I copied the change into my node_modules). Would you be able to update the dd-trace-js library to use the new version of `import-in-the-middle`? https://github.com/DataDog/dd-trace-js/issues/2221#issuecomment-1244794142 (related issue that will be fixed with this change)

**Comment by tlhunter** [comment]
@jamesone version `1.3.4` has just now been published! I'm now working on getting the change available in the next release of `dd-trace`.

**Comment by tlhunter** [comment]
We'll still probably release `dd-trace` soon, but I believe reinstalling the package should grab the latest version of `import-in-the-middle` since we [don't pin the version](https://github.com/DataDog/dd-trace-js/blob/e1f86e874ec23dae57bdbe02252a0f6bcc2e1215/package.json#L68) in `dd-trace`:



```json
    "import-in-the-middle": "^1.3.3",
```

**Comment by jamesone** [comment]
Awesome @tlhunter I can confirm that the [dd-trace issue](https://github.com/DataDog/dd-trace-js/issues/2221#issuecomment-1244794142) was fixed by this change
