### ISSUE TITLE
Incompatible with node 20.6+

### ISSUE THREAD

**Issue by lizthegrey** [DataDog/import-in-the-middle#33]
See https://nodejs.org/en/blog/release/v20.6.0#new-nodemodule-api-register-for-module-customization-hooks-new-initialize-hook which appears to have changed `--experimental-loader` chaining such that it no longer works correctly.

**Comment by Qard** [comment]
What's the behaviour you're seeing? We've tested on 20.6 and it worked for our tests. Are you encountering something different from #32?

**Comment by lizthegrey** [comment]
One data point is that we also chain `.pnp.js` from Yarn 4 to be able to then use IITM; I'll check first to see if the problem is there and get back to you.

**Comment by lizthegrey** [comment]
The problem seems to be https://github.com/nodejs/node/issues/50435 -- kudos to the person who found the minimal repro for this.

**Comment by lizthegrey** [comment]
This appears to be a problem strictly with Yarn PNP and not with Datadog IITM. And will be fixed in 20.11.0 anyways.

**Comment by lizthegrey** [comment]
Confirmed fixed in 20.11.0
